export const stories = [
	{
		"title_orig": "Mean girl",
		"title_cn": "坏女孩",
		"story_orig": "One day, a boy named Tim went for a walk. He saw a man with a cane. The man was old and walked slow. Tim wanted to help, so he walked with the man. The man was happy for the help. As they walked, they saw a girl named Sue. Sue was rude. She laughed at the man with the cane. \"Why do you walk so slow?\" Sue asked. The man felt sad. Tim did not like Sue's rude words. Tim had an idea. \"Let's count our steps,\" he said. The man and Tim started to count. \"One, two, three,\" they counted together. Sue stopped laughing and joined them. They all counted and walked together. Sue learned not to be rude, and they all became friends.",
		"story_cn": "有一天，一个叫蒂姆的男孩去散步。他看见一个拄着手杖的老人。这个老人年纪大，走得很慢。蒂姆想帮忙，于是他陪着老人一起走。老人因为得到帮助而感到高兴。当他们走着的时候，他们看到了一个叫苏的女孩。苏很无礼，她嘲笑拄着手杖的老人。\"你为什么走得这么慢？\" 苏问。老人感到难过。蒂姆不喜欢苏无礼的话。蒂姆有了一个主意。\"我们一起数步子吧，\"他说。老人和蒂姆开始数起步来。\"一，二，三，\"他们一起数。苏不再笑了，也加入了他们。他们一边数，一边一起走。苏学到了不该无礼，他们都成为了朋友。",
		"story_annotation": [
			"有一天/you3 yi1 tian1/One day",
			"，",
			"一个/yi1 ge4/a",
			"叫/jiao4/named",
			"蒂姆/Ti2 mu3/Tim",
			"的/de/(possessive)",
			"男孩/nan2 hai2/boy",
			"去/qu4/went",
			"散步/san4 bu4/for a walk",
			"。",
			"他/ta1/He",
			"看见/kan4 jian4/saw",
			"一个/yi1 ge4/a",
			"拄着/zhu3 zhe/supporting oneself with",
			"手杖/shou3 zhang4/cane",
			"的/de/(possessive)",
			"老人/lao3 ren2/old man",
			"。",
			"这个/zhe4 ge4/this",
			"老人/lao3 ren2/old man",
			"年纪/na4 ji4/age",
			"大/da4/old",
			"，",
			"走得/zou3 de/walked",
			"很/hen3/very",
			"慢/man4/slow",
			"。",
			"蒂姆/Ti2 mu3/Tim",
			"想/xiang3/wanted",
			"帮忙/bang1 mang2/to help",
			"，",
			"于是/yu2 shi4/so",
			"他/ta1/he",
			"陪着/pei2 zhe/accompanying",
			"老人/lao3 ren2/old man",
			"一起/yi4 qi3/together",
			"走/zou3/walk",
			"。",
			"老人/lao3 ren2/old man",
			"因为/yin1 wei4/because of",
			"得到/de2 dao4/got",
			"帮助/bang1 zhu4/help",
			"而/er2/and",
			"感到/gan3 dao4/felt",
			"高兴/gao1 xing4/happy",
			"。",
			"当/dang1/when",
			"他们/ta1 men/they",
			"走着/zou3 zhe/walking",
			"的/de/(possessive)",
			"时候/shi2 hou/time",
			"，",
			"他们/ta1 men/they",
			"看到/kan4 dao4/saw",
			"了/le/(past)",
			"一个/yi1 ge4/a",
			"叫/jiao4/named",
			"苏/Su1/Sue",
			"的/de/(possessive)",
			"女孩/nv3 hai2/girl",
			"。",
			"苏/Su1/Sue",
			"很/hen3/very",
			"无礼/wu2 li3/rude",
			"，",
			"她/ta1/she",
			"嘲笑/chao2 xiao4/laughed at",
			"拄着/zhu3 zhe/supporting oneself with",
			"手杖/shou3 zhang4/cane",
			"的/de/(possessive)",
			"老人/lao3 ren2/old man",
			"。",
			"\"",
			"你/ni3/you",
			"为什么/wei4 shen2 me/why",
			"走得/zou3 de/walk",
			"这么/zhe4 me/so",
			"慢/man4/slow",
			"？",
			"\"",
			"苏/Su1/Sue",
			"问/wen4/asked",
			"。",
			"老人/lao3 ren2/old man",
			"感到/gan3 dao4/felt",
			"难过/nan2 guo/sad",
			"。",
			"蒂姆/Ti2 mu3/Tim",
			"不/bu4/not",
			"喜欢/xi3 huan/like",
			"苏/Su1/Sue",
			"无礼/wu2 li3/rude",
			"的/de/(possessive)",
			"话/hua4/words",
			"。",
			"蒂姆/Ti2 mu3/Tim",
			"有/you3/had",
			"了/le/(past)",
			"一个/yi1 ge4/an",
			"主意/zhu3 yi4/idea",
			"。",
			"\"",
			"我们/wo3 men/we",
			"一起/yi4 qi3/together",
			"数步子/shu3 bu4 zi/count steps",
			"吧/ba/(suggestion particle)",
			"，",
			"\"",
			"他/ta1/he",
			"说/shuo1/said",
			"。",
			"老人/lao3 ren2/old man",
			"和/he2/and",
			"蒂姆/Ti2 mu3/Tim",
			"开始/kai1 shi3/started",
			"数起步来/shu3 qi3 bu4 lai/count steps",
			"。",
			"\"",
			"一/yi1/one",
			"，",
			"二/er4/two",
			"，",
			"三/san1/three",
			"，",
			"\"",
			"他们/ta1 men/they",
			"一起/yi4 qi3/together",
			"数/shu3/counted",
			"。",
			"苏/Su1/Sue",
			"不再/bu4 zai4/no longer",
			"笑/xiao4/laughed",
			"了/le/(past)",
			"，",
			"也/ye3/also",
			"加入/jia1 ru4/joined",
			"了/le/(past)",
			"他们/ta1 men/them",
			"。",
			"他们/ta1 men/they",
			"一边/yi1 bian/while",
			"数/shu3/count",
			"，",
			"一边/yi1 bian/while",
			"一起/yi4 qi3/together",
			"走/zou3/walk",
			"。",
			"苏/Su1/Sue",
			"学到/xue2 dao4/learned",
			"了/le/(past)",
			"不该/bu4 gai1/not to",
			"无礼/wu2 li3/be rude",
			"，",
			"他们/ta1 men/they",
			"都/dou1/all",
			"成为/cheng2 wei2/became",
			"了/le/(past)",
			"朋友/peng2 you/friends",
			"。"
		]
	},
	{
		"title_orig": "Bug story",
		"title_cn": "虫子的故事",
		"story_orig": "Once upon a time, there was a little bug. This bug was very persistent. He loved to write. One day, he met a big bug. The big bug said, \"I can write too!\" The little bug and the big bug became friends. They wrote together all the time. One day, they wrote a long story. They were very happy. But they did not know something unexpected was coming. The next day, they found their story was gone! They looked and looked, but could not find it. Then, they saw a tiny ant. The ant said, \"I took your story. I wanted to read it. It was very good!\" The little bug and the big bug were happy their story was liked. They let the ant keep it and they wrote a new story together.",
		"story_cn": "从前，有一只小虫子。这只小虫子非常坚持不懒。它喜欢写作。一天，它遇到了一只大虫子。大虫子说：“我也会写作！”小虫子和大虫子成了朋友。他们一直一起写作。一天，他们写了一个长故事。他们非常高兴。但是他们不知道，有意想不到的事情即将发生。第二天，他们发现他们的故事不见了！他们找啊找，但是找不到。然后，他们看到了一只小蚂蚁。蚂蚁说：“是我拿走了你们的故事。我想读它。它写得很好！”小虫子和大虫子很高兴他们的故事受到了喜欢。他们让蚂蚁保留了故事，并且他们一起写了一个新故事。",
		"story_annotation":[
            "狼",
            "从前/cong2 qian2/Once upon a time",
            "，",
            "有/you3/have",
            "一/yi1/one",
            "只/zhi1/measure word for insects",
            "小虫子/xiao3 chong2 zi/bug",
            "。",
            "这/zhe4/this",
            "只/zhi1/measure word for insects",
            "小虫子/xiao3 chong2 zi/bug",
            "非常/fei1 chang2/very",
            "坚持不懒/jian1 chi2 bu4 lan3/persistent",
            "。",
            "它/ta1/it",
            "喜欢/xi3 huan/love",
            "写作/xie3 zuo4/write",
            "。",
            "一天/yi1 tian1/One day",
            "，",
            "它/ta1/it",
            "遇到了/yu4 dao4 le/met",
            "一/yi1/one",
            "只/zhi1/measure word for insects",
            "大虫子/da4 chong2 zi/big bug",
            "。",
            "大虫子/da4 chong2 zi/big bug",
            "说/shuo1/said",
            "：",
            "“",
            "我/wo3/I",
            "也/ye3/also",
            "会/hui4/can",
            "写作/xie3 zuo4/write",
            "！",
            "”",
            "小虫子/xiao3 chong2 zi/little bug",
            "和/he2/and",
            "大虫子/da4 chong2 zi/big bug",
            "成了/chen2 le/became",
            "朋友/peng2 you/friends",
            "。",
            "他们/ta1 men/they",
            "一直/yi1 zhi2/all the time",
            "一起/yi4 qi3/together",
            "写作/xie3 zuo4/write",
            "。",
            "一天/yi1 tian1/One day",
            "，",
            "他们/ta1 men/they",
            "写了/xie3 le/wrote",
            "一个/yi1 ge4/a",
            "长/chang2/long",
            "故事/gu4 shi/story",
            "。",
            "他们/ta1 men/they",
            "非常/fei1 chang2/very",
            "高兴/gao1 xing/happy",
            "。",
            "但是/dan4 shi4/but",
            "他们/ta1 men/they",
            "不知道/bu4 zhi1 dao4/did not know",
            "，",
            "有意想不到的/you3 yi4 xiang3 bu4 dao4 de/unexpected",
            "事情/shi4 qing/thing",
            "即将/ji2 jiang/coming",
            "发生/fa1 sheng1/happen",
            "。",
            "第二天/di4 er4 tian1/The next day",
            "，",
            "他们/ta1 men/they",
            "发现/fa1 xian4/found",
            "他们的/ta1 men de/their",
            "故事/gu4 shi/story",
            "不见了/bu4 jian4 le/gone",
            "！",
            "他们/ta1 men/they",
            "找啊找/zhao3 a zhao3/looked and looked",
            "，",
            "但是/dan4 shi4/but",
            "找不到/zhao3 bu4 dao4/could not find",
            "。",
            "然后/ran2 hou4/Then",
            "，",
            "他们/ta1 men/they",
            "看到了/kan4 dao4 le/saw",
            "一只/yi1 zhi1/a",
            "小蚂蚁/xiao3 ma3 yi3/tiny ant",
            "。",
            "蚂蚁/ma3 yi3/ant",
            "说/shuo1/said",
            "：",
            "“",
            "是/shi4/is",
            "我/wo3/I",
            "拿走了/na2 zou3 le/took",
            "你们的/ni3 men de/your",
            "故事/gu4 shi/story",
            "。",
            "我/wo3/I",
            "想/xiang3/wanted",
            "读/du2/read",
            "它/ta1/it",
            "。",
            "它/ta1/it",
            "写得/xie3 de/written",
            "很/hen3/very",
            "好/hao3/good",
            "！",
            "”",
            "小虫子/xiao3 chong2 zi/little bug",
            "和/he2/and",
            "大虫子/da4 chong2 zi/big bug",
            "很高兴/hen3 gao1 xing/very happy",
            "他们的/ta1 men de/their",
            "故事/gu4 shi/story",
            "受到了/shou4 dao4 le/received",
            "喜欢/xi3 huan/liked",
            "。",
            "他们/ta1 men/they",
            "让/rang4/let",
            "蚂蚁/ma3 yi3/ant",
            "保留了/bao3 liu2 le/keep",
            "故事/gu4 shi/story",
            "，",
            "并且/bing4 qie/and",
            "他们/ta1 men/they",
            "一起/yi4 qi3/together",
            "写了/xie3 le/wrote",
            "一个/yi1 ge4/a",
            "新/xin1/new",
            "故事/gu4 shi/story",
            "。"
            ]
	}
]
